#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Android SDK
export ANDROID_HOME=/usr/local/opt/android-sdk


# Homebrew
export HOMEBREW_NO_ANALYTICS=1


# Node
export NVM_DIR="$HOME/.nvm"


# Notify
export DISABLE_NOTIFIER=true


# Python
export PROJECT_HOME="$HOME/Developer"
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
