#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# Node
export NVM_DIR="$HOME/.nvm"


# Notify
# export DISABLE_NOTIFIER=true


# Python
export PYENV_ROOT="$HOME/.pyenv"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export PROJECT_HOME="$HOME/Projects"
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'


# Vagrant
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion
export VAGRANT_CWD=$HOME/Projects/isl-cloud
